---
schema_version: 1
name: political_guardrail
on_failure: reject

rails:
  colang:
    # config.yml 파일과 같은 디렉토리에 있는 .co 파일을 지정
    flows:
      - path: political_rules.co

models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo